# docker-compose.yml
version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NEXTAUTH_URL=${NEXTAUTH_URL}
        - MONGODB_URI=${MONGODB_URI}
        - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
        - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
        - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
        - ENCRYPTION_KEY=${ENCRYPTION_KEY}
        - MONGODB_USER_PASSWORD=${MONGODB_USER_PASSWORD}
        - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
        - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
        - AWS_REGION=${AWS_REGION}
        - AWS_BUCKET=${AWS_BUCKET}
        - EMAIL_SERVER_PASSWORD=${EMAIL_SERVER_PASSWORD}
        - AUTH_RESEND_KEY=${AUTH_RESEND_KEY}
        - EMAIL_SERVER_USER=${EMAIL_SERVER_USER}
        - EMAIL_SERVER_HOST=${EMAIL_SERVER_HOST}
        - EMAIL_SERVER_PORT=${EMAIL_SERVER_PORT}
        - EMAIL_FROM=${EMAIL_FROM}
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - MONGODB_URI=mongodb://mongodb:27017/fever-lol
      - AUTH_GOOGLE_ID=${AUTH_GOOGLE_ID}
      - AUTH_GOOGLE_SECRET=${AUTH_GOOGLE_SECRET}
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - MONGODB_USER_PASSWORD=${MONGODB_USER_PASSWORD}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}
      - AWS_BUCKET=${AWS_BUCKET}
      - EMAIL_SERVER_PASSWORD=${EMAIL_SERVER_PASSWORD}
      - AUTH_RESEND_KEY=${AUTH_RESEND_KEY}
      - EMAIL_SERVER_USER=${EMAIL_SERVER_USER}
      - EMAIL_SERVER_HOST=${EMAIL_SERVER_HOST}
      - EMAIL_SERVER_PORT=${EMAIL_SERVER_PORT}
      - EMAIL_FROM=${EMAIL_FROM}
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_USER_PASSWORD}
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
