/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/DuedTRYsp8c
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Judson } from 'next/font/google'
import { Chivo } from 'next/font/google'

judson({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Button } from "@/components/ui/button"

export function PurchaseSuccessful() {
  return (
    <div className="flex flex-col items-center justify-center min-h-[100dvh] bg-background px-4 py-12 md:px-6">
      <div className="max-w-md w-full space-y-6">
        <div className="bg-card p-6 rounded-xl border-2 border-dashed border-muted">
          <div className="flex flex-col items-center justify-center space-y-4">
            <div className="relative w-20 h-20 rounded-full bg-primary/10 flex items-center justify-center">
              <div className="absolute -inset-2 rounded-full border-4 border-primary animate-ping" />
              <CircleCheckIcon className="text-green-500 size-10" />
            </div>
            <h2 className="text-2xl font-bold leading-tight">Purchase Successful!</h2>
            <p className="text-muted-foreground leading-normal">
              Thank you for your purchase. Your ticket details will be sent to the email address you provide.
            </p>
            <div className="w-full flex items-center space-x-2">
              <Label htmlFor="email" className="sr-only">
                Email
              </Label>
              <Input id="email" type="email" placeholder="Enter your email" className="w-full" />
              <Button
                type="submit"
                className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
              >
                Send
              </Button>
            </div>
          </div>
        </div>
        <div className="bg-card p-6 rounded-xl border-2 border-dashed border-muted">
          <div className="flex flex-col items-center justify-center space-y-4">
            <div className="w-32 h-32">
              <img
                src="/placeholder.svg"
                width={128}
                height={128}
                alt="QR Code"
                className="w-full h-full object-contain"
              />
            </div>
            <div className="space-y-1">
              <p className="text-sm font-medium leading-tight">Email Address</p>
              <p className="text-muted-foreground leading-normal">user@example.com</p>
            </div>
            <div className="space-y-1">
              <p className="text-sm font-medium leading-tight">Ticket Details</p>
              <p className="text-muted-foreground leading-normal">
                Event: Acme Conference 2024
                <br />
                Date: August 1, 2024
                <br />
                Time: 9:00 AM - 5:00 PM
              </p>
            </div>
          </div>
        </div>
        <div className="flex justify-center">
          <Button
            type="submit"
            className="inline-flex h-10 items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-1 focus-visible:ring-ring disabled:pointer-events-none disabled:opacity-50"
          >
            Send Ticket Details
          </Button>
        </div>
      </div>
    </div>
  )
}

function CircleCheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <circle cx="12" cy="12" r="10" />
      <path d="m9 12 2 2 4-4" />
    </svg>
  )
}


function XIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M18 6 6 18" />
      <path d="m6 6 12 12" />
    </svg>
  )
}
