/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/1oHMc66ATCj
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function Loading() {
  return (
    <div className="container mx-auto px-4 py-12">
      <div className="space-y-8">
        <div className="animate-pulse">
          <div className="h-8 w-32 rounded-md bg-muted" />
        </div>
        <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
          <div className="animate-pulse">
            <div className="h-40 rounded-md bg-muted" />
            <div className="mt-4 space-y-3">
              <div className="h-4 w-full rounded-md bg-muted" />
              <div className="h-4 w-3/4 rounded-md bg-muted" />
            </div>
          </div>
          <div className="animate-pulse">
            <div className="h-40 rounded-md bg-muted" />
            <div className="mt-4 space-y-3">
              <div className="h-4 w-full rounded-md bg-muted" />
              <div className="h-4 w-3/4 rounded-md bg-muted" />
            </div>
          </div>
          <div className="animate-pulse">
            <div className="h-40 rounded-md bg-muted" />
            <div className="mt-4 space-y-3">
              <div className="h-4 w-full rounded-md bg-muted" />
              <div className="h-4 w-3/4 rounded-md bg-muted" />
            </div>
          </div>
          <div className="animate-pulse">
            <div className="h-40 rounded-md bg-muted" />
            <div className="mt-4 space-y-3">
              <div className="h-4 w-full rounded-md bg-muted" />
              <div className="h-4 w-3/4 rounded-md bg-muted" />
            </div>
          </div>
          <div className="animate-pulse">
            <div className="h-40 rounded-md bg-muted" />
            <div className="mt-4 space-y-3">
              <div className="h-4 w-full rounded-md bg-muted" />
              <div className="h-4 w-3/4 rounded-md bg-muted" />
            </div>
          </div>
          <div className="animate-pulse">
            <div className="h-40 rounded-md bg-muted" />
            <div className="mt-4 space-y-3">
              <div className="h-4 w-full rounded-md bg-muted" />
              <div className="h-4 w-3/4 rounded-md bg-muted" />
            </div>
          </div>
        </div>
      </div>
    </div>
  )
}
